/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import assignment.manager.BookingManager;
import assignment.manager.CustomerValidator;
import assignment.manager.DateManager;
import assignment.manager.FileManager;
import static assignment.manager.FileManager.FiletoList;
import assignment.manager.PaymentManager;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class EditPanel extends javax.swing.JFrame {
    private String CID, COD, RoomID, DOS, Name, IC, Contact, Email, bookingdataFile = "customerdata.txt";
    private Date CIDinDate, CODinDate;
    private int selectedBookingRow;

    public EditPanel(int SelectedBookingRow, String[] selectedData) throws ParseException {
        this.selectedBookingRow = SelectedBookingRow;
        this.CID = selectedData[5];
        this.COD = selectedData[6];
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        CIDinDate = format.parse(CID);
        CODinDate = format.parse(COD);
        this.RoomID = selectedData[4];
        this.DOS = selectedData[7];
        this.Name = selectedData[0];
        this.IC = selectedData[3];
        this.Contact = selectedData[1];
        this.Email = selectedData[2];
        initComponents();
    }
    
    public double getTotalPaymentValue(String RoomID){
        PaymentManager pm = new PaymentManager(Integer.parseInt(DOS),Integer.parseInt(RoomID) );
        double totalPaymentValue = pm.getTotalPayment();
        return totalPaymentValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditTitle = new javax.swing.JLabel();
        CheckInDateFL = new javax.swing.JLabel();
        CIDForm = new com.toedter.calendar.JDateChooser();
        RoomIDFL = new javax.swing.JLabel();
        RoomIDForm = new javax.swing.JTextField();
        CustomerNameFL = new javax.swing.JLabel();
        CustomerNameForm = new javax.swing.JTextField();
        ContactFL = new javax.swing.JLabel();
        ContactForm = new javax.swing.JTextField();
        CheckOutDateFL = new javax.swing.JLabel();
        CODForm = new com.toedter.calendar.JDateChooser();
        DoSFL = new javax.swing.JLabel();
        DoSForm = new javax.swing.JTextField();
        ICFL = new javax.swing.JLabel();
        ICForm = new javax.swing.JFormattedTextField();
        CustomerEmailFL = new javax.swing.JLabel();
        EmailForm = new javax.swing.JTextField();
        TotalPaymentFL = new javax.swing.JLabel();
        totalPaymentForm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        EditTitle.setFont(new java.awt.Font("Encode Sans Medium", 1, 18)); // NOI18N
        EditTitle.setText("Edit Booking's Details");

        CheckInDateFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CheckInDateFL.setText("Check-In Date: ");

        CIDForm.setToolTipText("");
        CIDForm.setEnabled(false);
        CIDForm.setDate(CIDinDate);

        RoomIDFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        RoomIDFL.setText("Room's ID");

        RoomIDForm.setText(RoomID);

        CustomerNameFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CustomerNameFL.setText("Customer's Name: ");

        CustomerNameForm.setText(Name);

        ContactFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        ContactFL.setText("Contact Number: ");

        ContactForm.setText(Contact);
        ContactForm.setToolTipText("");

        CheckOutDateFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CheckOutDateFL.setText("Check-Out Date: ");

        CODForm.setDate(CODinDate);
        CODForm.setEnabled(false);

        DoSFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        DoSFL.setText("Day of Stay");

        DoSForm.setEditable(false);
        DoSForm.setText(DOS);
        DoSForm.setEnabled(false);

        ICFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        ICFL.setText("IC / Passport: ");

        try {
            ICForm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ICForm.setText(IC );

        CustomerEmailFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CustomerEmailFL.setText("Customer's Email: ");

        EmailForm.setText(Email);

        TotalPaymentFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        TotalPaymentFL.setText("Total Payment: ");

        totalPaymentForm.setEditable(false);
        totalPaymentForm.setText(String.format("%.2f", getTotalPaymentValue(RoomID)));
        totalPaymentForm.setEnabled(false);

        jButton1.setText("Save Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CheckInDateFL)
                                .addComponent(CIDForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContactForm, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(CustomerNameForm))
                            .addComponent(EditTitle)
                            .addComponent(TotalPaymentFL)
                            .addComponent(ContactFL)
                            .addComponent(totalPaymentForm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomIDForm))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CustomerEmailFL)
                                .addComponent(ICForm)
                                .addComponent(CheckOutDateFL)
                                .addComponent(CODForm, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(DoSForm)
                                .addComponent(EmailForm, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RoomIDFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DoSFL)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustomerNameFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ICFL)
                        .addGap(116, 116, 116))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckOutDateFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CODForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EditTitle)
                        .addGap(18, 18, 18)
                        .addComponent(CheckInDateFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CIDForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDFL)
                    .addComponent(DoSFL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoSForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomIDForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ICFL)
                    .addComponent(CustomerNameFL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerNameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactFL)
                    .addComponent(CustomerEmailFL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TotalPaymentFL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPaymentForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date checkInDate = CIDForm.getDate();
        Date checkOutDate = CODForm.getDate();
        String roomresult = RoomIDForm.getText();
        int roomID = Integer.parseInt(roomresult);
        boolean isRoomAvailable = true;
        
        try {
            String[] unavailableRoom = DateManager.getDateRangeandReturnUnavailableRoom(checkInDate, checkOutDate);
            int[] unavailableRoomInInt = new int[unavailableRoom.length];
            for (int i=0; i< unavailableRoom.length; i++){
                if (roomID != Integer.parseInt(unavailableRoom[i])){
                    unavailableRoomInInt[i] = Integer.parseInt(unavailableRoom[i]);
                }
            }
            
            for (int i=0; i<unavailableRoomInInt.length; i++){
                if((unavailableRoomInInt[i] == roomID)||((roomID<1)||(roomID>20))){
                    isRoomAvailable = false;
                    break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(EditPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (!isRoomAvailable){
            JOptionPane.showMessageDialog(null, "Room ID: "+roomID+" is not available! Please select again!");
        }else{
            int DoS = Integer.parseInt((DoSForm.getText()).replaceAll("[^0-9]", ""));
            String customerName = CustomerNameForm.getText();
            String icNumber = ICForm.getText();
            String contactNumber = ContactForm.getText();
            String customerEmail = EmailForm.getText();
            CustomerValidator validator = new CustomerValidator();
            PaymentManager pm = new PaymentManager( DoS, Integer.parseInt(roomresult));

            boolean checkName = validator.validateCustomerName(customerName);
            boolean checkEmail = validator.validateCustomerEmail(customerEmail);
            boolean checkIC = validator.validateCustomerICNumber(icNumber);
            boolean checkContact = validator.validateCustomerContact(contactNumber);

            // check if any of the input are empty
            if (customerName.isEmpty() || icNumber.isEmpty() || contactNumber.isEmpty() || customerEmail.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill up all the details");

            } else {

                //Check for validations
                if (!checkName){
                    JOptionPane.showMessageDialog(null, "Please enter a valid name!");
                } else if (!checkContact){
                    JOptionPane.showMessageDialog(null, "Please enter a valid contact number!");
                } else if (!checkIC){
                    JOptionPane.showMessageDialog(null, "Please enter a IC number!");
                } else if (!checkEmail){
                    JOptionPane.showMessageDialog(null, "Please enter a valid email!");
                } else {
                    BookingManager bm = new BookingManager(checkInDate, checkOutDate, roomresult, DoS, customerName, icNumber, contactNumber, customerEmail);
                    bm.setCustomerName(customerName);
                    bm.setCustomerEmail(customerEmail);
                    bm.setICNumber(icNumber);
                    bm.setContactNumber(contactNumber);

                    String CIDinStr = bm.getCheckInDateinStr();
                    String CODinStr = bm.getCheckOutDateinStr();
                    double totalPayment = pm.getTotalPayment();

                    String newBookingDetails = customerName+", "+contactNumber+", "+customerEmail+", "+icNumber+", "+roomresult+", "+CIDinStr+", "+CODinStr+", "+DoS+", "+totalPayment;
                    try {
                        ReplaceDataAndSaveToFile(newBookingDetails);
                    } catch (IOException ex) {
                        Logger.getLogger(EditPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ReplaceDataAndSaveToFile(String newBookingData) throws IOException{
        FileManager fm = new FileManager();
        String[] newBookingDataList = newBookingData.split(", ");
        System.out.println(Arrays.toString(newBookingDataList));
        Object[][] data = FiletoList(bookingdataFile);
        data[selectedBookingRow] = newBookingDataList;
        System.out.println(Arrays.toString(data));
        int option = JOptionPane.showConfirmDialog(null, "Confirm Save the modified data?", "Confirm Detail", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.OK_OPTION){
                    fm.RewriteArrToFile(data, bookingdataFile);
                    //back to Booking Panel
                    this.dispose();
                }
        

    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CIDForm;
    private com.toedter.calendar.JDateChooser CODForm;
    private javax.swing.JLabel CheckInDateFL;
    private javax.swing.JLabel CheckOutDateFL;
    private javax.swing.JLabel ContactFL;
    private javax.swing.JTextField ContactForm;
    private javax.swing.JLabel CustomerEmailFL;
    private javax.swing.JLabel CustomerNameFL;
    private javax.swing.JTextField CustomerNameForm;
    private javax.swing.JLabel DoSFL;
    private javax.swing.JTextField DoSForm;
    private javax.swing.JLabel EditTitle;
    private javax.swing.JTextField EmailForm;
    private javax.swing.JLabel ICFL;
    private javax.swing.JFormattedTextField ICForm;
    private javax.swing.JLabel RoomIDFL;
    private javax.swing.JTextField RoomIDForm;
    private javax.swing.JLabel TotalPaymentFL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField totalPaymentForm;
    // End of variables declaration//GEN-END:variables
}
