/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package assignment;

import assignment.manager.*;
import java.io.IOException;
import java.text.ParseException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class HotelRoomPage extends javax.swing.JFrame {

    public HotelRoomPage() throws IOException {
        this.totalEarningValue = displayM.getTotalEarning();
        this.totalCustomerValue = Integer.toString(displayM.getTotalCustomer());
        initComponents();
        this.bookingFile = "customerdata.txt";
        buttons[0] = r0101;
        buttons[1] = r0102;
        buttons[2] = r0103;
        buttons[3] = r0104;
        buttons[4] = r0105;
        buttons[5] = r0106;
        buttons[6] = r0107;
        buttons[7] = r0108;
        buttons[8] = r0109;
        buttons[9] = r0110;
        buttons[10] = r0201;
        buttons[11] = r0202;
        buttons[12] = r0203;
        buttons[13] = r0204;
        buttons[14] = r0205;
        buttons[15] = r0206;
        buttons[16] = r0207;
        buttons[17] = r0208;
        buttons[18] = r0209;
        buttons[19] = r0210;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomSelection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Bookbtn = new javax.swing.JButton();
        Viewbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        BookSec = new javax.swing.JPanel();
        BookingPanel = new javax.swing.JPanel();
        DisplayPanel = new javax.swing.JPanel();
        TotalCustomerLabel = new javax.swing.JLabel();
        TotalEarningLabel = new javax.swing.JLabel();
        TotalCustomerValue = new javax.swing.JLabel();
        TotalEarningValue = new javax.swing.JLabel();
        BookingSec = new javax.swing.JPanel();
        CheckInDate = new com.toedter.calendar.JDateChooser();
        CheckInLabel = new javax.swing.JLabel();
        CheckOutDate = new com.toedter.calendar.JDateChooser();
        CheckOutLabel = new javax.swing.JLabel();
        Reservebtn = new javax.swing.JButton();
        BGPic = new javax.swing.JLabel();
        SelectRoomPanel = new javax.swing.JPanel();
        hotelroompic1 = new javax.swing.JLabel();
        hotelroompic2 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        firstfloorroomlabel = new javax.swing.JLabel();
        BookRoombtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        r0101 = new javax.swing.JRadioButton();
        r0102 = new javax.swing.JRadioButton();
        r0103 = new javax.swing.JRadioButton();
        r0104 = new javax.swing.JRadioButton();
        r0105 = new javax.swing.JRadioButton();
        r0106 = new javax.swing.JRadioButton();
        r0107 = new javax.swing.JRadioButton();
        r0108 = new javax.swing.JRadioButton();
        r0109 = new javax.swing.JRadioButton();
        r0110 = new javax.swing.JRadioButton();
        secondfloorroomlabel = new javax.swing.JLabel();
        r0201 = new javax.swing.JRadioButton();
        r0202 = new javax.swing.JRadioButton();
        r0203 = new javax.swing.JRadioButton();
        r0204 = new javax.swing.JRadioButton();
        r0205 = new javax.swing.JRadioButton();
        r0206 = new javax.swing.JRadioButton();
        r0207 = new javax.swing.JRadioButton();
        r0208 = new javax.swing.JRadioButton();
        r0209 = new javax.swing.JRadioButton();
        r0210 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        pricefor1stfloor = new javax.swing.JLabel();
        pricefor2ndfloor = new javax.swing.JLabel();
        BookingFormPanel = new javax.swing.JPanel();
        CODForm = new com.toedter.calendar.JDateChooser();
        RoomTitle = new javax.swing.JLabel();
        CIDForm = new com.toedter.calendar.JDateChooser();
        CheckInDateFL = new javax.swing.JLabel();
        CheckOutDateFL = new javax.swing.JLabel();
        CustomerNameFL = new javax.swing.JLabel();
        CustomerNameForm = new javax.swing.JTextField();
        ICFL = new javax.swing.JLabel();
        ContactFL = new javax.swing.JLabel();
        ContactForm = new javax.swing.JTextField();
        CustomerEmailFL = new javax.swing.JLabel();
        EmailForm = new javax.swing.JTextField();
        RoomIDFL = new javax.swing.JLabel();
        RoomIDForm = new javax.swing.JTextField();
        DoSFL = new javax.swing.JLabel();
        DoSForm = new javax.swing.JTextField();
        FormConfirmbtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        ICForm = new javax.swing.JFormattedTextField();
        PaymentTitle = new javax.swing.JLabel();
        PaymentMethodLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PaymentMethodtext = new javax.swing.JComboBox<>();
        TotalLabel = new javax.swing.JLabel();
        SubtotalLabel = new javax.swing.JLabel();
        ServiceTaxLabel = new javax.swing.JLabel();
        TourismTaxLabel = new javax.swing.JLabel();
        subtotalValue = new javax.swing.JLabel();
        serviceTaxValue = new javax.swing.JLabel();
        tourismTaxValue = new javax.swing.JLabel();
        totalValue = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingDetailTable = new javax.swing.JTable();
        BookingDetailsLabel = new javax.swing.JLabel();
        Searchbar = new javax.swing.JTextField();
        Categories = new javax.swing.JComboBox<>();
        Searchbtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();
        Refreshbtn = new javax.swing.JButton();
        Receiptbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HotelBookingPage");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        SideBar.setBackground(new java.awt.Color(237, 238, 204));
        SideBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 173, 128), 1, true));
        SideBar.setFocusable(false);

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotellogo.png"))); // NOI18N

        Bookbtn.setBackground(new java.awt.Color(143, 139, 94));
        Bookbtn.setFont(new java.awt.Font("Encode Sans", 1, 14)); // NOI18N
        Bookbtn.setForeground(new java.awt.Color(255, 255, 255));
        Bookbtn.setText("Book");
        Bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookbtnActionPerformed(evt);
            }
        });

        Viewbtn.setBackground(new java.awt.Color(143, 139, 94));
        Viewbtn.setFont(new java.awt.Font("Encode Sans", 1, 14)); // NOI18N
        Viewbtn.setForeground(new java.awt.Color(255, 255, 255));
        Viewbtn.setText("View");
        Viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbtnActionPerformed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(143, 139, 94));
        Exitbtn.setFont(new java.awt.Font("Encode Sans", 1, 14)); // NOI18N
        Exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exitbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Logo)
                .addGap(67, 67, 67)
                .addComponent(Bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(Viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.add(SideBar, java.awt.BorderLayout.WEST);

        BookSec.setLayout(new java.awt.CardLayout());

        BookingPanel.setBackground(new java.awt.Color(238, 233, 223));
        BookingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisplayPanel.setBackground(new java.awt.Color(217, 217, 184));
        DisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 91, 33), 5));

        TotalCustomerLabel.setBackground(new java.awt.Color(204, 204, 204));
        TotalCustomerLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        TotalCustomerLabel.setForeground(new java.awt.Color(51, 51, 51));
        TotalCustomerLabel.setText("Total Customers:");

        TotalEarningLabel.setBackground(new java.awt.Color(204, 204, 204));
        TotalEarningLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        TotalEarningLabel.setForeground(new java.awt.Color(51, 51, 51));
        TotalEarningLabel.setText("Total Earning:");

        TotalCustomerValue.setBackground(new java.awt.Color(204, 204, 204));
        TotalCustomerValue.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        TotalCustomerValue.setForeground(new java.awt.Color(51, 51, 51));
        TotalCustomerValue.setText(totalCustomerValue);

        TotalEarningValue.setBackground(new java.awt.Color(204, 204, 204));
        TotalEarningValue.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        TotalEarningValue.setForeground(new java.awt.Color(51, 51, 51));
        TotalEarningValue.setText("RM "+(String.format("%.2f", totalEarningValue)));

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TotalCustomerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalCustomerValue)
                .addGap(35, 35, 35)
                .addComponent(TotalEarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalEarningValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCustomerValue)
                    .addComponent(TotalEarningLabel)
                    .addComponent(TotalCustomerLabel)
                    .addComponent(TotalEarningValue))
                .addGap(26, 26, 26))
        );

        BookingPanel.add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 500, 90));

        BookingSec.setBackground(new java.awt.Color(217, 217, 184));
        BookingSec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 115, 75), 3, true));

        CheckInDate.setBackground(new java.awt.Color(222, 201, 146));
        CheckInDate.setForeground(new java.awt.Color(51, 51, 51));
        CheckInDate.setDateFormatString("dd/MM/yyyy");
        CheckInDate.setDoubleBuffered(false);
        CheckInDate.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CheckInDate.setMinSelectableDate(new Date());
        CheckInDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                addPropertyChangeListener(evt);
            }
        });

        CheckInLabel.setBackground(new java.awt.Color(204, 204, 204));
        CheckInLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        CheckInLabel.setForeground(new java.awt.Color(51, 51, 51));
        CheckInLabel.setText("Check In Date");

        CheckOutDate.setBackground(new java.awt.Color(222, 201, 146));
        CheckOutDate.setForeground(new java.awt.Color(51, 51, 51));
        CheckOutDate.setDateFormatString("dd/MM/yyyy");
        CheckOutDate.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CheckOutDate.setMinSelectableDate(new Date());

        CheckOutLabel.setBackground(new java.awt.Color(204, 204, 204));
        CheckOutLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 18)); // NOI18N
        CheckOutLabel.setForeground(new java.awt.Color(51, 51, 51));
        CheckOutLabel.setText("Check Out Date");

        Reservebtn.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 14)); // NOI18N
        Reservebtn.setText("Reserve");
        Reservebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservebtnPressed(evt);
            }
        });

        javax.swing.GroupLayout BookingSecLayout = new javax.swing.GroupLayout(BookingSec);
        BookingSec.setLayout(BookingSecLayout);
        BookingSecLayout.setHorizontalGroup(
            BookingSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingSecLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(BookingSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckInLabel)
                    .addComponent(CheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, Short.MAX_VALUE)
                .addGroup(BookingSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOutLabel))
                .addGap(60, 60, 60))
            .addGroup(BookingSecLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Reservebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookingSecLayout.setVerticalGroup(
            BookingSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingSecLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(BookingSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingSecLayout.createSequentialGroup()
                        .addComponent(CheckInLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingSecLayout.createSequentialGroup()
                        .addComponent(CheckOutLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(Reservebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        BookingPanel.add(BookingSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 500, 270));

        BGPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/studio-heritage-3.jpg"))); // NOI18N
        BookingPanel.add(BGPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 950, -1));

        BookSec.add(BookingPanel, "Booking1card");

        SelectRoomPanel.setBackground(new java.awt.Color(238, 233, 223));

        hotelroompic1.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        hotelroompic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotelroom1.jpg"))); // NOI18N

        hotelroompic2.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        hotelroompic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotelroom2.jpg"))); // NOI18N

        firstfloorroomlabel.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 14)); // NOI18N
        firstfloorroomlabel.setText("First Floor Room View");

        BookRoombtn.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 14)); // NOI18N
        BookRoombtn.setText("Book");
        BookRoombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookRoombtnActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RoomSelection.add(r0101);
        r0101.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0101.setText("1");

        RoomSelection.add(r0102);
        r0102.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0102.setText("2");

        RoomSelection.add(r0103);
        r0103.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0103.setText("3");

        RoomSelection.add(r0104);
        r0104.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0104.setText("4");

        RoomSelection.add(r0105);
        r0105.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0105.setText("5");

        RoomSelection.add(r0106);
        r0106.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0106.setText("6");

        RoomSelection.add(r0107);
        r0107.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0107.setText("7");

        RoomSelection.add(r0108);
        r0108.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0108.setText("8");

        RoomSelection.add(r0109);
        r0109.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0109.setText("9");

        RoomSelection.add(r0110);
        r0110.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0110.setText("10");

        secondfloorroomlabel.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 14)); // NOI18N
        secondfloorroomlabel.setText("Second Floor Room View");

        RoomSelection.add(r0201);
        r0201.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0201.setText("11");

        RoomSelection.add(r0202);
        r0202.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0202.setText("12");

        RoomSelection.add(r0203);
        r0203.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0203.setText("13");

        RoomSelection.add(r0204);
        r0204.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0204.setText("14");

        RoomSelection.add(r0205);
        r0205.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0205.setText("15");

        RoomSelection.add(r0206);
        r0206.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0206.setText("16");

        RoomSelection.add(r0207);
        r0207.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0207.setText("17");

        RoomSelection.add(r0208);
        r0208.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0208.setText("18");

        RoomSelection.add(r0209);
        r0209.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0209.setText("19");

        RoomSelection.add(r0210);
        r0210.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        r0210.setText("20");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pricefor1stfloor.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        pricefor1stfloor.setText("RM350");

        pricefor2ndfloor.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        pricefor2ndfloor.setText("RM500");

        javax.swing.GroupLayout SelectRoomPanelLayout = new javax.swing.GroupLayout(SelectRoomPanel);
        SelectRoomPanel.setLayout(SelectRoomPanelLayout);
        SelectRoomPanelLayout.setHorizontalGroup(
            SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRoomPanelLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRoomPanelLayout.createSequentialGroup()
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(firstfloorroomlabel))
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0107)
                                .addGap(18, 18, 18)
                                .addComponent(r0108)
                                .addGap(18, 18, 18)
                                .addComponent(r0109))
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0104)
                                .addGap(18, 18, 18)
                                .addComponent(r0105)
                                .addGap(18, 18, 18)
                                .addComponent(r0106))
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0101)
                                .addGap(18, 18, 18)
                                .addComponent(r0102)
                                .addGap(18, 18, 18)
                                .addComponent(r0103))
                            .addComponent(r0110)
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(pricefor1stfloor)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRoomPanelLayout.createSequentialGroup()
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0204)
                                .addGap(18, 18, 18)
                                .addComponent(r0205)
                                .addGap(18, 18, 18)
                                .addComponent(r0206))
                            .addComponent(r0210)
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0201)
                                .addGap(18, 18, 18)
                                .addComponent(r0202)
                                .addGap(18, 18, 18)
                                .addComponent(r0203))
                            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                                .addComponent(r0207)
                                .addGap(18, 18, 18)
                                .addComponent(r0208)
                                .addGap(18, 18, 18)
                                .addComponent(r0209)))
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRoomPanelLayout.createSequentialGroup()
                        .addComponent(secondfloorroomlabel)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRoomPanelLayout.createSequentialGroup()
                        .addComponent(pricefor2ndfloor)
                        .addGap(207, 207, 207))))
            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(264, 264, 264)
                        .addComponent(BookRoombtn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(hotelroompic1)
                        .addGap(56, 56, 56)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(hotelroompic2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectRoomPanelLayout.setVerticalGroup(
            SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hotelroompic1)
                    .addComponent(hotelroompic2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondfloorroomlabel)
                    .addComponent(firstfloorroomlabel))
                .addGap(31, 31, 31)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0101)
                            .addComponent(r0102)
                            .addComponent(r0103))
                        .addGap(26, 26, 26)
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0104)
                            .addComponent(r0105)
                            .addComponent(r0106))
                        .addGap(27, 27, 27)
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0109)
                            .addComponent(r0107)
                            .addComponent(r0108))
                        .addGap(27, 27, 27)
                        .addComponent(r0110))
                    .addGroup(SelectRoomPanelLayout.createSequentialGroup()
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0201)
                            .addComponent(r0202)
                            .addComponent(r0203))
                        .addGap(26, 26, 26)
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0204)
                            .addComponent(r0205)
                            .addComponent(r0206))
                        .addGap(27, 27, 27)
                        .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r0209)
                            .addComponent(r0207)
                            .addComponent(r0208))
                        .addGap(27, 27, 27)
                        .addComponent(r0210)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricefor1stfloor)
                    .addComponent(pricefor2ndfloor))
                .addGap(18, 18, 18)
                .addGroup(SelectRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookRoombtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        BookSec.add(SelectRoomPanel, "Booking2card");

        BookingFormPanel.setBackground(new java.awt.Color(238, 233, 223));

        CODForm.setEnabled(false);

        RoomTitle.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 24)); // NOI18N
        RoomTitle.setText("Customer's Booking Details\n");

        CIDForm.setEnabled(false);

        CheckInDateFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CheckInDateFL.setText("Check-In Date: ");

        CheckOutDateFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CheckOutDateFL.setText("Check-Out Date: ");

        CustomerNameFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CustomerNameFL.setText("Customer's Name: ");

        ICFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        ICFL.setText("IC / Passport: ");

        ContactFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        ContactFL.setText("Contact Number: ");

        ContactForm.setText("+60");
        ContactForm.setToolTipText("");

        CustomerEmailFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CustomerEmailFL.setText("Customer's Email: ");

        RoomIDFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        RoomIDFL.setText("Room's ID");

        RoomIDForm.setEditable(false);
        RoomIDForm.setEnabled(false);
        RoomIDForm.setFocusable(false);

        DoSFL.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        DoSFL.setText("Day of Stay");

        DoSForm.setEditable(false);
        DoSForm.setEnabled(false);
        DoSForm.setFocusable(false);

        FormConfirmbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 14)); // NOI18N
        FormConfirmbtn.setText("Confirm");
        FormConfirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormConfirmbtnActionPerformed(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        try {
            ICForm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        PaymentTitle.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        PaymentTitle.setText("Payments");

        PaymentMethodLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        PaymentMethodLabel.setText("Payment Methods: ");

        PaymentMethodtext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "E-Wallet QR Payment", "Online Banking", "Credit / Debit Card" }));

        TotalLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        TotalLabel.setText("Total:");

        SubtotalLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        SubtotalLabel.setText("Sub-total:");

        ServiceTaxLabel.setText("Service Tax (10%):");

        TourismTaxLabel.setText("Tourism Tax (RM10 per night): ");

        subtotalValue.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N

        serviceTaxValue.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N

        tourismTaxValue.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N

        totalValue.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N

        javax.swing.GroupLayout BookingFormPanelLayout = new javax.swing.GroupLayout(BookingFormPanel);
        BookingFormPanel.setLayout(BookingFormPanelLayout);
        BookingFormPanelLayout.setHorizontalGroup(
            BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(879, Short.MAX_VALUE))
            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerNameForm)
                    .addComponent(CIDForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckInDateFL)
                    .addComponent(RoomIDFL)
                    .addComponent(RoomIDForm)
                    .addComponent(CustomerNameFL)
                    .addComponent(ContactFL)
                    .addComponent(ContactForm, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerEmailFL)
                    .addComponent(ICFL)
                    .addComponent(CheckOutDateFL)
                    .addComponent(CODForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoSFL)
                    .addComponent(DoSForm)
                    .addComponent(EmailForm, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICForm, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingFormPanelLayout.createSequentialGroup()
                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingFormPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                                .addComponent(PaymentTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PaymentMethodtext, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentMethodLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingFormPanelLayout.createSequentialGroup()
                                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ServiceTaxLabel)
                                            .addComponent(SubtotalLabel)
                                            .addComponent(TourismTaxLabel)
                                            .addComponent(TotalLabel))
                                        .addGap(185, 185, 185)
                                        .addComponent(totalValue))
                                    .addComponent(subtotalValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(serviceTaxValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tourismTaxValue, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(BookingFormPanelLayout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomTitle)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingFormPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FormConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        BookingFormPanelLayout.setVerticalGroup(
            BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoomTitle)
                .addGap(43, 43, 43)
                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingFormPanelLayout.createSequentialGroup()
                        .addComponent(CheckInDateFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CIDForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RoomIDFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoomIDForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerNameFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerNameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ContactFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingFormPanelLayout.createSequentialGroup()
                        .addComponent(CheckOutDateFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CODForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoSFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoSForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ICFL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(CustomerEmailFL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ICForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingFormPanelLayout.createSequentialGroup()
                        .addGap(53, 130, Short.MAX_VALUE)
                        .addComponent(totalValue)
                        .addGap(29, 29, 29))
                    .addGroup(BookingFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PaymentTitle)
                        .addGap(4, 4, 4)
                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtotalLabel)
                            .addComponent(subtotalValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ServiceTaxLabel)
                                    .addComponent(serviceTaxValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TourismTaxLabel)
                                    .addComponent(tourismTaxValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TotalLabel))
                            .addGroup(BookingFormPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(PaymentMethodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PaymentMethodtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(FormConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        BookSec.add(BookingFormPanel, "card4");

        ViewPanel.setBackground(new java.awt.Color(238, 233, 223));

        BookingDetailTable.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        BookingDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            bookingData,
            new String [] {
                "Name", "Contact", "Email", "IC", "Room ID", "Check-In Date", "Check-Out Date", "Days of Stay", "Total Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BookingDetailTable.setFocusable(false);
        BookingDetailTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(BookingDetailTable);

        BookingDetailsLabel.setFont(new java.awt.Font("Encode Sans", 1, 24)); // NOI18N
        BookingDetailsLabel.setText("Booking's Details");

        Searchbar.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N

        Categories.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Contact", "Email", "IC", "Room ID", "Check-In Date", "Check-Out Date", "Days of Stay", "Total Payment" }));

        Searchbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        Resetbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        Deletebtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        Editbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        Refreshbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Refreshbtn.setText("Refresh");
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });

        Receiptbtn.setFont(new java.awt.Font("Encode Sans SemiBold", 0, 12)); // NOI18N
        Receiptbtn.setText("Receipt");
        Receiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addComponent(BookingDetailsLabel)
                                .addGap(105, 105, 105)
                                .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Resetbtn)))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addComponent(Editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Receiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanelLayout.createSequentialGroup()
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BookingDetailsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Searchbtn)
                            .addComponent(Resetbtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BookSec.add(ViewPanel, "card5");

        jPanel1.add(BookSec, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setUnavailableRoomToDisable(){
        
        try {
               unavailableRoomList = DateManager.getDateRangeandReturnUnavailableRoom(checkInDate, checkOutDate);
            for (String unavailableRoomList1 : unavailableRoomList) {
                int buttonIndex = Integer.parseInt(unavailableRoomList1) - 1;
                buttons[buttonIndex].setEnabled(false);
            }
           } catch (IOException ex) {
               Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    
    public void setbackRoomAvailablity(){
        for (int i=0; i<20; i++){
            buttons[i].setEnabled(true);
        }
    }
    
    ////////////////////////////////////////////////////////////////////////
    /*                      Booking Panel                                */
    ///////////////////////////////////////////////////////////////////////
    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void ReservebtnPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservebtnPressed
        
        try{
            //get dates
            checkInDate = CheckInDate.getDate();
            checkOutDate = CheckOutDate.getDate();
        
            //Call Booking Manager Class
            reserve = new BookingManager(checkInDate, checkOutDate);
            
            //Check both date validation
            result = reserve.Verify();

            if (result) {
                setUnavailableRoomToDisable();
                BookingPanel.setVisible(false);
                SelectRoomPanel.setVisible(true);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Please select a date!");
        }
        
    }//GEN-LAST:event_ReservebtnPressed

   
    //Validation for JDateChooser. User cannot pick the dates before today and check-out date cannot be the date before check-in date.
    private void addPropertyChangeListener(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_addPropertyChangeListener
       if ("date".equals(evt.getPropertyName())){
           
           checkInDate = CheckInDate.getDate();
           checkOutDate = CheckOutDate.getDate();
           
           if (checkInDate != null){
               //Set the minimum selectable date for the check-out date chooser
               Calendar minCheckOutDate = Calendar.getInstance();
               minCheckOutDate.setTime(checkInDate);
               minCheckOutDate.add(Calendar.DAY_OF_MONTH, 1); //add one day to the check-in date
               CheckOutDate.setMinSelectableDate(minCheckOutDate.getTime());
           }
       }
    }//GEN-LAST:event_addPropertyChangeListener

    
    ////////////////////////////////////////////////////////////////////////
    /*                      Select Room Panel                             */
    ///////////////////////////////////////////////////////////////////////

    private void BookRoombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookRoombtnActionPerformed
        
        //get the selected radio button
        JRadioButton selectedButton = null;
        Enumeration<AbstractButton> roombtns = RoomSelection.getElements();
        //loop inside button group and pick up the first element return true 
        while (roombtns.hasMoreElements()){
            AbstractButton roombtn = roombtns.nextElement();
            if (roombtn.isSelected()){
                selectedButton = (JRadioButton) roombtn;
                break;
            }
        }
        

        DoS = DateManager.countDays(checkInDate, checkOutDate);
        //if the radiobutton grp is not null, fetch the selected button's value to the next panel and show next panel
        if (selectedButton != null){
            roomresult = selectedButton.getText();
            CIDForm.setDate(checkInDate);
            CODForm.setDate(checkOutDate);
            RoomIDForm.setText(roomresult);
            DoSForm.setText(DoS+" Day/s");
            pm = new PaymentManager((int) DoS,Integer.parseInt(roomresult));
            
            subtotalValue.setText(String.format("%.2f",pm.getPaymentb4Tax()));
            serviceTaxValue.setText(String.format("%.2f",pm.getServiceTax()));
            tourismTaxValue.setText(String.format("%.2f",pm.getTourismTax()));
            totalValue.setText("RM "+String.format("%.2f",pm.getTotalPayment()));
            
            SelectRoomPanel.setVisible(false);
            BookingFormPanel.setVisible(true);
        } else {
            //ask user select one room
            JOptionPane.showMessageDialog(null, "Please select a room!");
        }
        
    }//GEN-LAST:event_BookRoombtnActionPerformed
    
    //Show Booking Panel (for back button)
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NavigateToBookingPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Show Select Room Panel (for back button)
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        BookingPanel.setVisible(false);
        SelectRoomPanel.setVisible(true);
        BookingFormPanel.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed
    
    public void NavigateToBookingPanel(){
        try {
            totalEarningValue = dm.getTotalEarning();
            totalCustomerValue = Integer.toString(dm.getTotalCustomer());
        } catch (IOException ex) {
            Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        BookingPanel.setVisible(true);
        SelectRoomPanel.setVisible(false);
        BookingFormPanel.setVisible(false);
        ViewPanel.setVisible(false);
        setbackRoomAvailablity();
        TotalEarningValue.setText("RM "+(String.format("%.2f", totalEarningValue)));
        TotalCustomerValue.setText(totalCustomerValue);
    }
    
    public void NavigateToViewPanel() throws IOException{
        BookingPanel.setVisible(false);
        SelectRoomPanel.setVisible(false);
        BookingFormPanel.setVisible(false);
        ViewPanel.setVisible(true);
        RefreshView();
    }
    
    ////////////////////////////////////////////////////////////////////////
    /*                      Booking Form Panel                            */
    ///////////////////////////////////////////////////////////////////////
    @SuppressWarnings("empty-statement")
    private void FormConfirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormConfirmbtnActionPerformed
        
        checkInDate = CheckInDate.getDate();
        checkOutDate = CheckOutDate.getDate();
        roomresult = RoomIDForm.getText();
        intDoS = Integer.parseInt((DoSForm.getText()).replaceAll("[^0-9]", ""));
        customerName = CustomerNameForm.getText();
        icNumber = ICForm.getText();
        contactNumber = ContactForm.getText();
        customerEmail = EmailForm.getText();
        paymentMethod = PaymentMethodtext.getSelectedItem().toString();
        CustomerValidator validator = new CustomerValidator();
        pm = new PaymentManager( intDoS, Integer.parseInt(roomresult));
        
        //boolean for validation
        checkEmail = validator.validateCustomerEmail(customerEmail);
        checkName = validator.validateCustomerName(customerName);
        checkIC = validator.validateCustomerICNumber(icNumber);
        checkContact = validator.validateCustomerContact(contactNumber);

        // check if any of the input are empty
        if (customerName.isEmpty() || icNumber.isEmpty() || contactNumber.isEmpty() || customerEmail.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up all the details");
            
        } else {
            
            //Check for validations
            if (!checkName){
                JOptionPane.showMessageDialog(null, "Please enter a valid name!");
            } else if (!checkContact){
                JOptionPane.showMessageDialog(null, "Please enter a valid contact number!");
            } else if (!checkIC){
                JOptionPane.showMessageDialog(null, "Please enter a IC number!");
            } else if (!checkEmail){
                JOptionPane.showMessageDialog(null, "Please enter a valid email!");
            } else {
                // all JTextFields are filled, convert the input and create a new booking

                //use BookingManage class to compile all the data
                BookingManager bm = new BookingManager(checkInDate, checkOutDate, roomresult, intDoS, customerName, icNumber, contactNumber, customerEmail, paymentMethod);
                bm.setCustomerName(customerName);
                bm.setCustomerEmail(customerEmail);
                bm.setICNumber(icNumber);
                bm.setContactNumber(contactNumber);

                bookingDetailsDisplay = (
                        "Check-In Date: "+bm.getCheckInDateinStr()+"\n"+
                        "Check-Out Date: "+bm.getCheckOutDateinStr()+"\n"+
                        "Room ID: "+bm.getRoomID()+"\n"+
                        "Day of Stay: "+bm.getDoS()+"\n"+
                        "Customer Name: "+bm.getCustomerName()+"\n"+
                        "Customer Email: "+bm.getCustomerEmail()+"\n"+
                        "IC/Passport Number: "+bm.getICNumber()+"\n"+
                        "Contact Number: "+bm.getContactNumber()+"\n"+
                        "Payment Method: "+bm.getPaymentMethod()+"\n"+
                        "Total Payment: RM "+(String.format("%.2f",pm.getTotalPayment())));

                CIDinStr = bm.getCheckInDateinStr();
                CODinStr = bm.getCheckOutDateinStr();
                totalPayment = pm.getTotalPayment();

                bookingDetails = (customerName+", "+contactNumber+", "+customerEmail+", "+icNumber+", "+roomresult+", "+CIDinStr+", "+CODinStr+", "+intDoS+", "+totalPayment);

                //ask user to confirm the customer's details
                option = JOptionPane.showConfirmDialog(null, bookingDetailsDisplay, "Confirm Detail", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.OK_OPTION){
                    fm.AddToFile(bookingDetails, bookingFile);
                    //back to Booking Panel
                    NavigateToBookingPanel();
                    ClearSelectionData();
                }
            }
            
        }
    }//GEN-LAST:event_FormConfirmbtnActionPerformed
    
    public Object[][] getBookingData() throws IOException{
        bookingData = FileManager.FiletoList(bookingFile);
        return bookingData;
    }
    
    public void ClearSelectionData(){
        //set back all the var to null
        CheckInDate.setDate(null);
        CheckOutDate.setDate(null);
        RoomSelection.clearSelection();
        CustomerNameForm.setText(null);
        ICForm.setText(null);
        ContactForm.setText("+60");
        EmailForm.setText(null);
        PaymentMethodtext.setSelectedIndex(0);
        setbackRoomAvailablity();
    }
    
    private void BookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookbtnActionPerformed
        NavigateToBookingPanel();
    }//GEN-LAST:event_BookbtnActionPerformed

    private void ViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbtnActionPerformed
        try {
            NavigateToViewPanel();
        } catch (IOException ex) {
            Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewbtnActionPerformed

    
    ////////////////////////////////////////////////////////////////////////
    /*                         View Panel                                 */
    ///////////////////////////////////////////////////////////////////////
    
    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed

        searchObj = Searchbar.getText();
        categories = Categories.getSelectedIndex();
        Search search = new Search(searchObj,categories,bookingFile);
        try {
            searchData = search.SearchandReturn();
            searchModel = new DefaultTableModel(searchData, categoriesName);
            BookingDetailTable.setModel(searchModel);
        } catch (IOException ex) {
            Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchbtnActionPerformed

    public void RefreshView() throws IOException{
        Searchbar.setText(null);
        bookingData = getBookingData();
        resetModel = new DefaultTableModel(bookingData, categoriesName){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        BookingDetailTable.setModel(resetModel);
    }
    
    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        try {
            RefreshView();
        } catch (IOException ex) {
            Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        selectedBookingIndex = BookingDetailTable.getSelectedRow();
        
        if (selectedBookingIndex != -1){
            option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entire row?", "Confirm Delete Booking's Details?", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.OK_OPTION){
                deleteModel = (DefaultTableModel) BookingDetailTable.getModel();
                deleteModel.removeRow(selectedBookingIndex);
                BookingDetailTable.repaint();
                try {
                    fm.saveTableDataToFile(BookingDetailTable, bookingFile);
                } catch (IOException ex) {
                    Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select the row you want to delete!");
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        selectedBookingRow = BookingDetailTable.getSelectedRow();
        
        if (selectedBookingRow != -1){
            TableModel model = BookingDetailTable.getModel();
            String[] selectedData = new String[model.getColumnCount()];
            
            for (int i=0; i<model.getColumnCount(); i++){
                selectedData[i] = (String) model.getValueAt(selectedBookingRow, i);
            }
            try {
                EditPanel EP = new EditPanel(selectedBookingRow, selectedData);
                EP.setVisible(true);
                
            } catch (ParseException ex) {
                Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select the row you want to edit!");
        }
    }//GEN-LAST:event_EditbtnActionPerformed

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed
        try {
            RefreshView();
        } catch (IOException ex) {
            Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshbtnActionPerformed

    private void ReceiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptbtnActionPerformed
        selectedBookingRow = BookingDetailTable.getSelectedRow();
        
        if (selectedBookingRow != -1){
            TableModel model = BookingDetailTable.getModel();
            String[] selectedData = new String[model.getColumnCount()];
            
            for (int i=0; i<model.getColumnCount(); i++){
                selectedData[i] = (String) model.getValueAt(selectedBookingRow, i);
            }
            try {
                Receipt r = new Receipt(selectedBookingRow, selectedData);
                r.setVisible(true);
                
            } catch (ParseException ex) {
                Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select the row you want to edit!");
        }
    }//GEN-LAST:event_ReceiptbtnActionPerformed
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelRoomPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new HotelRoomPage().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HotelRoomPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private double totalEarningValue;
    private DisplayManager displayM = new DisplayManager(), dm = new DisplayManager();
    private final JRadioButton[] buttons = new JRadioButton[20];
    private DefaultTableModel searchModel, resetModel, deleteModel;
    private Object[][] bookingData, searchData = null;
    private BookingManager reserve;
    private PaymentManager pm;
    private FileManager fm = new FileManager();
    private boolean checkEmail, checkName, checkIC, checkContact, result;
    private double totalPayment;
    private int intDoS, option, categories, selectedBookingIndex, selectedBookingRow;
    private Date checkInDate, checkOutDate; 
    private String[] unavailableRoomList = null;
    private final String[] categoriesName = {"Name", "Contact", "Email", "IC", "Room ID", "Check-In Date", "Check-Out Date", "Days of Stay", "Total Payment"};
    private final String bookingFile;
    private String roomresult, icNumber, customerName, customerEmail, contactNumber, bookingDetailsDisplay, bookingDetails, CIDinStr, CODinStr, paymentMethod, searchObj, totalCustomerValue;
    private long DoS;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGPic;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BookRoombtn;
    private javax.swing.JPanel BookSec;
    private javax.swing.JButton Bookbtn;
    private javax.swing.JTable BookingDetailTable;
    private javax.swing.JLabel BookingDetailsLabel;
    private javax.swing.JPanel BookingFormPanel;
    private javax.swing.JPanel BookingPanel;
    private javax.swing.JPanel BookingSec;
    private com.toedter.calendar.JDateChooser CIDForm;
    private com.toedter.calendar.JDateChooser CODForm;
    private javax.swing.JComboBox<String> Categories;
    private com.toedter.calendar.JDateChooser CheckInDate;
    private javax.swing.JLabel CheckInDateFL;
    private javax.swing.JLabel CheckInLabel;
    private com.toedter.calendar.JDateChooser CheckOutDate;
    private javax.swing.JLabel CheckOutDateFL;
    private javax.swing.JLabel CheckOutLabel;
    private javax.swing.JLabel ContactFL;
    private javax.swing.JTextField ContactForm;
    private javax.swing.JLabel CustomerEmailFL;
    private javax.swing.JLabel CustomerNameFL;
    private javax.swing.JTextField CustomerNameForm;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel DoSFL;
    private javax.swing.JTextField DoSForm;
    private javax.swing.JButton Editbtn;
    private javax.swing.JTextField EmailForm;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton FormConfirmbtn;
    private javax.swing.JLabel ICFL;
    private javax.swing.JFormattedTextField ICForm;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel PaymentMethodLabel;
    private javax.swing.JComboBox<String> PaymentMethodtext;
    private javax.swing.JLabel PaymentTitle;
    private javax.swing.JButton Receiptbtn;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JButton Reservebtn;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JLabel RoomIDFL;
    private javax.swing.JTextField RoomIDForm;
    private javax.swing.ButtonGroup RoomSelection;
    private javax.swing.JLabel RoomTitle;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JPanel SelectRoomPanel;
    private javax.swing.JLabel ServiceTaxLabel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel SubtotalLabel;
    private javax.swing.JLabel TotalCustomerLabel;
    private javax.swing.JLabel TotalCustomerValue;
    private javax.swing.JLabel TotalEarningLabel;
    private javax.swing.JLabel TotalEarningValue;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TourismTaxLabel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton Viewbtn;
    private javax.swing.JLabel firstfloorroomlabel;
    private javax.swing.JLabel hotelroompic1;
    private javax.swing.JLabel hotelroompic2;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pricefor1stfloor;
    private javax.swing.JLabel pricefor2ndfloor;
    private javax.swing.JRadioButton r0101;
    private javax.swing.JRadioButton r0102;
    private javax.swing.JRadioButton r0103;
    private javax.swing.JRadioButton r0104;
    private javax.swing.JRadioButton r0105;
    private javax.swing.JRadioButton r0106;
    private javax.swing.JRadioButton r0107;
    private javax.swing.JRadioButton r0108;
    private javax.swing.JRadioButton r0109;
    private javax.swing.JRadioButton r0110;
    private javax.swing.JRadioButton r0201;
    private javax.swing.JRadioButton r0202;
    private javax.swing.JRadioButton r0203;
    private javax.swing.JRadioButton r0204;
    private javax.swing.JRadioButton r0205;
    private javax.swing.JRadioButton r0206;
    private javax.swing.JRadioButton r0207;
    private javax.swing.JRadioButton r0208;
    private javax.swing.JRadioButton r0209;
    private javax.swing.JRadioButton r0210;
    private javax.swing.JLabel secondfloorroomlabel;
    private javax.swing.JSeparator separator1;
    private javax.swing.JLabel serviceTaxValue;
    private javax.swing.JLabel subtotalValue;
    private javax.swing.JLabel totalValue;
    private javax.swing.JLabel tourismTaxValue;
    // End of variables declaration//GEN-END:variables

}
