/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import assignment.manager.DateManager;
import assignment.manager.PaymentManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;


/**
 *
 * @author USER
 */
public class Receipt extends javax.swing.JFrame {
    
    private String CID, COD, RoomID, DOS, Name, IC, Contact, Email;
    private int selectedBookingRow;
    private double subTotal, serviceTax, tourismTax, totalPayment;
    
    
    public Receipt(int SelectedBookingRow, String[] selectedData) throws ParseException {
        this.selectedBookingRow = SelectedBookingRow;
        this.CID = selectedData[5];
        this.COD = selectedData[6];
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        this.RoomID = selectedData[4];
        this.DOS = selectedData[7];
        this.Name = selectedData[0];
        this.IC = selectedData[3];
        this.Contact = selectedData[1];
        this.Email = selectedData[2];
        PaymentManager pm = new PaymentManager(Integer.parseInt(DOS),Integer.parseInt(RoomID));
        subTotal = (pm.getPaymentb4Tax());
        serviceTax = pm.getServiceTax();
        tourismTax = pm.getTourismTax();
        totalPayment = pm.getTotalPayment();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HotelNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TimeLabel = new javax.swing.JLabel();
        ReceiptLabel = new javax.swing.JLabel();
        TimeData = new javax.swing.JLabel();
        CIDLabel = new javax.swing.JLabel();
        CODLabel = new javax.swing.JLabel();
        RoomIDLabel = new javax.swing.JLabel();
        DoSLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerEmailLabel = new javax.swing.JLabel();
        CustomerICLabel = new javax.swing.JLabel();
        CustomerContactLabel = new javax.swing.JLabel();
        CIDData = new javax.swing.JLabel();
        CODData = new javax.swing.JLabel();
        RoomIDData = new javax.swing.JLabel();
        DoSData = new javax.swing.JLabel();
        CustomerNameData = new javax.swing.JLabel();
        CustomerEmailData = new javax.swing.JLabel();
        CustomerICData = new javax.swing.JLabel();
        CustomerContactData = new javax.swing.JLabel();
        SubtotalLabel = new javax.swing.JLabel();
        ServiceTaxLabel = new javax.swing.JLabel();
        TourismTaxLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        SubtotalData = new javax.swing.JLabel();
        ServiceTaxData = new javax.swing.JLabel();
        TourismTaxData = new javax.swing.JLabel();
        TotalData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HotelNameLabel.setFont(new java.awt.Font("Encode Sans Medium", 1, 18)); // NOI18N
        HotelNameLabel.setText("Hotel MeWhy");

        TimeLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        TimeLabel.setText("Time:");

        ReceiptLabel.setFont(new java.awt.Font("Encode Sans ExtraBold", 1, 24)); // NOI18N
        ReceiptLabel.setText("Receipt");

        TimeData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        TimeData.setText(DateManager.getCurrentDateAndTime());

        CIDLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CIDLabel.setText("Check-In Date:");

        CODLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CODLabel.setText("Check-Out Date: ");

        RoomIDLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        RoomIDLabel.setText("Room ID: ");

        DoSLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        DoSLabel.setText("Day of Stay(s):");

        CustomerNameLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerNameLabel.setText("Customer Name:");

        CustomerEmailLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerEmailLabel.setText("Customer Email:");

        CustomerICLabel.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerICLabel.setText("Customer IC:");

        CustomerContactLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        CustomerContactLabel.setText("Customer Contact:");

        CIDData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CIDData.setText(CID);

        CODData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CODData.setText(COD);

        RoomIDData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        RoomIDData.setText(RoomID);

        DoSData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        DoSData.setText(DOS);

        CustomerNameData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerNameData.setText(Name);

        CustomerEmailData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerEmailData.setText(Email);

        CustomerICData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerICData.setText(IC);

        CustomerContactData.setFont(new java.awt.Font("Encode Sans", 0, 12)); // NOI18N
        CustomerContactData.setText(Contact);

        SubtotalLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        SubtotalLabel.setText("Sub-total:");

        ServiceTaxLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        ServiceTaxLabel.setText("Service Tax (10%):");

        TourismTaxLabel.setFont(new java.awt.Font("Encode Sans Medium", 0, 12)); // NOI18N
        TourismTaxLabel.setText("Tourism Tax (RM10 per night): ");

        TotalLabel.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        TotalLabel.setText("Total:");

        SubtotalData.setText(Double.toString(subTotal)
        );

        ServiceTaxData.setText(Double.toString(serviceTax));

        TourismTaxData.setText(Double.toString(tourismTax));

        TotalData.setFont(new java.awt.Font("Encode Sans SemiBold", 1, 18)); // NOI18N
        TotalData.setText("RM "+Double.toString(totalPayment));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(HotelNameLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(ReceiptLabel)
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TimeLabel)
                                                .addGap(111, 111, 111)
                                                .addComponent(TimeData))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CIDLabel)
                                                    .addComponent(CODLabel)
                                                    .addComponent(RoomIDLabel)
                                                    .addComponent(DoSLabel)
                                                    .addComponent(CustomerNameLabel)
                                                    .addComponent(CustomerEmailLabel)
                                                    .addComponent(CustomerICLabel)
                                                    .addComponent(CustomerContactLabel))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CIDData)
                                                    .addComponent(RoomIDData)
                                                    .addComponent(CODData)
                                                    .addComponent(DoSData)
                                                    .addComponent(CustomerNameData)
                                                    .addComponent(CustomerEmailData)
                                                    .addComponent(CustomerICData)
                                                    .addComponent(CustomerContactData))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TotalLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TotalData))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TourismTaxLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TourismTaxData))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ServiceTaxLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ServiceTaxData))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(SubtotalLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SubtotalData)))
                                        .addGap(47, 47, 47)))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HotelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLabel)
                    .addComponent(TimeData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIDLabel)
                    .addComponent(CIDData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CODLabel)
                    .addComponent(CODData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDLabel)
                    .addComponent(RoomIDData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoSLabel)
                    .addComponent(DoSData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerEmailLabel)
                    .addComponent(CustomerEmailData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerICLabel)
                    .addComponent(CustomerICData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerContactLabel)
                    .addComponent(CustomerContactData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubtotalLabel)
                    .addComponent(SubtotalData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceTaxLabel)
                    .addComponent(ServiceTaxData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TourismTaxLabel)
                    .addComponent(TourismTaxData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel)
                    .addComponent(TotalData))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CIDData;
    private javax.swing.JLabel CIDLabel;
    private javax.swing.JLabel CODData;
    private javax.swing.JLabel CODLabel;
    private javax.swing.JLabel CustomerContactData;
    private javax.swing.JLabel CustomerContactLabel;
    private javax.swing.JLabel CustomerEmailData;
    private javax.swing.JLabel CustomerEmailLabel;
    private javax.swing.JLabel CustomerICData;
    private javax.swing.JLabel CustomerICLabel;
    private javax.swing.JLabel CustomerNameData;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel DoSData;
    private javax.swing.JLabel DoSLabel;
    private javax.swing.JLabel HotelNameLabel;
    private javax.swing.JLabel ReceiptLabel;
    private javax.swing.JLabel RoomIDData;
    private javax.swing.JLabel RoomIDLabel;
    private javax.swing.JLabel ServiceTaxData;
    private javax.swing.JLabel ServiceTaxLabel;
    private javax.swing.JLabel SubtotalData;
    private javax.swing.JLabel SubtotalLabel;
    private javax.swing.JLabel TimeData;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel TotalData;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TourismTaxData;
    private javax.swing.JLabel TourismTaxLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
